# ExtraCompostables - Compost the world!
# An open-source project by Mykyta (@nkomarn)
# https://github.com/nkomarn/extra-compostables

compostables:
  BAMBOO: 30 # Material : Chance (1-100)
  GRASS: 30
  COBWEB: 30
  STRING: 30
  ROTTEN_FLESH: 30
  SPIDER_EYE: 30
  EGG: 30
  SUGAR: 30
  DEAD_BUSH: 30
  BEEF: 50
  CHICKEN: 50
  MUTTON: 50
  PORKCHOP: 50
  RABBIT: 50
  COD: 50
  SALMON: 50
  TROPICAL_FISH: 50
  PUFFERFISH: 50
  GLOW_INK_SAC: 50
  BEETROOT_SOUP: 50
  BRAIN_CORAL: 50
  BUBBLE_CORAL: 50
  FIRE_CORAL: 50
  HORN_CORAL: 50
  TUBE_CORAL: 50
  DEAD_BRAIN_CORAL: 50
  DEAD_BUBBLE_CORAL: 50
  DEAD_FIRE_CORAL: 50
  DEAD_HORN_CORAL: 50
  DEAD_TUBE_CORAL: 50
  BRAIN_CORAL_FAN: 50
  BUBBLE_CORAL_FAN: 50
  FIRE_CORAL_FAN: 50
  HORN_CORAL_FAN: 50
  TUBE_CORAL_FAN: 50
  DEAD_BRAIN_CORAL_FAN: 50
  DEAD_BUBBLE_CORAL_FAN: 50
  DEAD_FIRE_CORAL_FAN: 50
  DEAD_HORN_CORAL_FAN: 50
  DEAD_TUBE_CORAL_FAN: 50
  BRAIN_CORAL_BLOCK: 50
  BUBBLE_CORAL_BLOCK: 50
  FIRE_CORAL_BLOCK: 50
  HORN_CORAL_BLOCK: 50
  TUBE_CORAL_BLOCK: 50
  DEAD_BRAIN_CORAL_BLOCK: 50
  DEAD_BUBBLE_CORAL_BLOCK: 50
  DEAD_FIRE_CORAL_BLOCK: 50
  DEAD_HORN_CORAL_BLOCK: 50
  DEAD_TUBE_CORAL_BLOCK: 50
  FERMENTED_SPIDER_EYE: 50
  GLISTERING_MELON_SLICE: 50
  TURTLE_EGG: 50
  COOKED_BEEF: 65
  COOKED_CHICKEN: 65
  COOKED_MUTTON: 65
  COOKED_PORKCHOP: 65
  COOKED_RABBIT: 65
  COOKED_COD: 65
  COOKED_SALMON: 65
  HONEYCOMB: 65
  PHANTOM_MEMBRANE: 65
  POISONOUS_POTATO: 65
  RABBIT_FOOT: 65
  RABBIT_STEW: 65
  SUSPICIOUS_STEW: 65
  HONEY_BLOCK: 85
  HONEYCOMB_BLOCK: 85
  ZOMBIE_HEAD: 100
  DRAGON_HEAD: 100

# For a full list of viable materials, visit this page:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html