# ExtraCompostables - Compost the world!
# An open-source project by Mykyta (@nkomarn)
# https://github.com/nkomarn/extra-compostables

compostables:
  BAMBOO: 30 # Material : Chance (1-100)
  GRASS: 30
  HONEYCOMB: 65
  ZOMBIE_HEAD: 100

# For a full list of viable materials, visit this page:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html